spring.application.name=Project
spring.h2.console.enabled=true
spring.jpa.show-sql=true

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:./test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size = 120MB
spring.servlet.multipart.max-request-size = 120MB


#spring.ai.openai.api-key={GEMINI_KEY}
spring.ai.openai.api-key=AIzaSyCDvImo52jTUSoxw14Or-sIQaF7bVefLc0 
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=gemini-2.5-flash

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lielhorovitshot@gmail.com
spring.mail.password=xnvajmtvjzdmtnkt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com




   